---
dependencies:
  cupertino_icons: ^0.1.2
  path_provider: ^0.5.0
  socket_io : ^0.9.0+2
  adhara_socket_io: ^0.1.10
  flutter:
    sdk: flutter
  web_socket_channel: ^1.0.9

description: "Flutter client app for master thesis"
dev_dependencies:
  flutter_test:
    sdk: flutter
environment:
  sdk: ">=2.1.0 <3.0.0"
flutter:
  assets:
  - assets/images/dog.jpeg
  - assets/images/dog_small.jpeg
  - assets/images/stars.jpg
  - assets/sounds/big_sound.mp3
  - assets/sounds/small_sound.wav
  uses-material-design: true
name: flutter_client
version: 1.0.0+1
